<!DOCTYPE html>
<HTML>
<HEAD>
<?php require_once("build/head.php"); ?>
<link rel="stylesheet" type="text/css" href="assets/css/projects.css">
<link rel="stylesheet" type="text/css" href="assets/css/beambeats.css">
</HEAD>
<BODY class="bg-beambeats">

<?php require_once("build/header.php"); ?>

<div id="wrapper">
    <section id="introduction">
        <div class="content tall">
            <div class="vertical-align center">
                <h1 class="project-title white text-center">Beam Beats</h1>
                <p class="project-subtitle white text-center">interactive installation</p>
                <div class="project-links">
                    <a href="assets/projects/beam-beats/deck.pdf"><div class="deck-button">deck</div></a> <a href="http://beambeats.cias.rit.edu/visualization/"><div class="deck-button">website</div></a> <a href="http://beambeats.cias.rit.edu/"><div class="deck-button">promotional website</div></a> <a href="http://bandthelazers.tumblr.com/"><div class="deck-button">process blog</div></a> <a href="https://github.com/YouMeKim/beam-beats"><div class="deck-button">github</div></a><!-- <a href="https://github.com/brendan-w/beam-beats"><div class="deck-button">github (hardware)</div></a> <a href="https://github.com/nickMinnoe/BeamBeatsVis"><div class="deck-button">github (visualization)</div></a> -->
                </div>
            </div>
        </div>
    </section>
    <section id="overview" class="bg-white">
        <div class="content">
            <h1>Beam Beats</h1>
            <p>Beam Beats is a collaborative musical installation created in collaboration with <a target="_blank" href="http://www.rockhall.com/">The Rock & Roll Hall of Fame</a>. We were challenged to create a unique exhibit to encourage visitors of the Rock & Roll Hall of Fame to take their experience home with them. Our team of 9 designers and developers worked tirelessly for 5 months from conception to prototyping to create Beam Beats.</p>
            <div class="half-first">
                <iframe src="https://player.vimeo.com/video/166989126" width="100%" height="280px" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
            <div class="half">
            <iframe src="https://player.vimeo.com/video/167090553" width="100%" height="280px" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
            <div class="two-third">
                <h4>Contributions</h4>
                <p>During this project, my main responsibilities included website development and database management. The visualization website allows users to view all the images generated by the Beam Beats installation and allows users to edit these image to create their own unique image. The users may then email themselves their creations. The MySQL database records metadata on every visualization that was created and is used to display the visualizations on the website.</p>
            </div>
            <div class="third">
                <h4>Team</h4>
                <p>
                    <a target="_blank" href="http://www.ayechanpmoe.com/">Aye Chan Moe</a><br>
                    <a target="_blank" href="http://camrobinsondesign.com/">Cameron Robinson</a><br>
                    <a target="_blank" href="http://courtneyboire.com/">Courtney Boire</a><br>
                    <a target="_blank" href="http://maxwhitehead.com/">Max Whitehead</a><br>
                    <a target="_blank" href="https://github.com/nickminnoe">Nick Minnoe</a><br>
                    <a target="_blank" href="http://www.nicoledombi.com/">Nicole Dombi</a><br>
                    <a target="_blank" href="http://oxg7534.cias.rit.edu/#/">Olivia Grace</a><br>
                    <a target="_blank" href="http://brendan-w.com/">Brendan Whitfield</a>
                </p>
            </div>
        </div>
    </section>
    <section id="website" class="bg-grey-light">
        <div class="content">
            <h1>Website</h1>
            <p>Once users complete their Beam Beats experience, they can visit our website to view their creations. Using the ID number provided to them during their visit, they can search for their visualization and edit it using a variety of filters. Once they are complete editing their images, they are able to email their creations to themselves.</p>
            <h3>Technologies</h3>
            <p>The main website is primarily written in HTML, CSS, and JavaScript. We decided to utilize JavaScript as the main scripting language for this website due to it's need to display real-time data as it's being served to the database. In addition, I was hoping to experiment more with front-end technologies.</p>
            <p>Although most scripts are written in JavaScript, there are 2 PHP services that were created for the website:</p>
            <ol>
                <li><strong><a href="https://github.com/YouMeKim/beam-beats/blob/master/email.php">Email</a></strong> – Send formatted HTML email with creation to user</li>
                <li><strong><a href="https://github.com/YouMeKim/beam-beats/blob/master/acceptVis.php">Accept Visualization</a></strong> – Accept Base64 string POST data which is sent from the Processing script</li>
            </ol>
            <h3>Linking the Installation to the Website</h3>
            <p>Once users are finished creating their visualization, 5 images are sent to the server: an overview visualization and four different images highlighting specific colors. All the data is sent to the <a href="https://github.com/YouMeKim/beam-beats/blob/master/acceptVis.php">Accept Visualization</a> PHP script as POST data, written in base64 string. These images are then converted to transparent PNGs and saved to the server. The database only contains the visualization ID and their respective file names for reference.</p>
            <h3>API</h3>
            <p>During the creation of the website, we ran into a couple issues:</p>
            <ol>
                <li>We needed a way to live-update data as they were fed to the database from our installation.</li>
                <li>We needed a system to keep track of current IDs to be able to assign incoming users of their ID.</li>
            </ol>
            <p>To solve these issues, I decided to implement a quick API to access all visualizations on the database, which can be accessed <a href="http://beambeats.cias.rit.edu/visualization/visualizations.php">here</a>. The API returns an array of JSON objects containing information about each visualization such as ID and file name. This way, we were able to keep track of what current ID we were serving during our exhibition at the Imagine RIT festival. In addition, we were able to update the list of visualizations when the start button is clicked on the website.</p>
            <h3>Database</h3>
            <p>During the early stages of development, we explored several DBMS options. Due to our document focused nature, we initially opted for MongoDB, and although we wanted to utlize MongoDB for our database, due to time constraints and lack of expertise, we ended up sticking with MySQL.</p>
            <div class="half-first">
                <img style="width:100%;" alt="database" src="assets/projects/beam-beats/database.png">
            </div>
            <div class="half">
                <p>After several iterations, we finalized the database design and decided on three tables:</p>
                <p>
                    <strong>visualization</strong> (<u>id</u>, name, imageall, imagepur, imagered, imageyel, imageblu, datecreated, datemodified)<br>
                    <strong>creation</strong> (<u>id</u>, originalid, image, datecreated, datemodified)<br>
                    <strong>history</strong> (<u>id</u>, creationid, datesent, email)<br>
                </p>
                <p>Images are stored on the server, which is then referenced by the database via a relative url path.</p>
            </div>
        </div>
    </section>
    <section id="branding" class="bg-white">
        <div class="content">
            <h1>Branding</h1>
            <p>We wanted our exhibit to reflect an energetic, intriguing, and dramatic environment; like that of a rock concert.</p>
            <img id="moodboard" alt="moodboard" src="assets/projects/beam-beats/moodboard.png">
            <h4>Logo</h4>
            <img class="fourth-first" alt="logo1" src="assets/projects/beam-beats/logo4.png">
            <img class="fourth" alt="logo3" src="assets/projects/beam-beats/logo3.png">
            <img class="fourth" alt="logo4" src="assets/projects/beam-beats/logo1.png">
            <img class="fourth" alt="logo2" src="assets/projects/beam-beats/logo2.png">
            <p style="margin-top: 270px;">We went through several iterations of our logo before we decided upon a simple, clean logo.</p>
        </div>
    </section>
    <section id="visualization" class="bg-grey-light">
        <div class="content">
            <h1>Visualization</h1>
            <div class="half-first">
                <iframe src="https://player.vimeo.com/video/168103720" width="100%" height="280px" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
            <div class="half" style="height:290px;">
                <p>After many brainstorming and sketching sessions, we decided that our favorite solution was a circular visualization that was otherwise literal in it's translation. We used the note, octave, beat, and duration and wrapped the timeline around a circle so when complete, you can't tell where it starts or ends.</p>
            </div>
            <div class="fourth-first">
                <h4>NOTE = POSITION</h4>
                <p>The note played on the beam is translated onto the visual as a position relative to the center of the circle.</p>
            </div>
            <div class="fourth">
                <h4>OCTAVE = COLOR</h4>
                <p>Since each beam is a color, the color of the note placed on the visual is representative of which beam was played.</p>
            </div>
            <div class="fourth">
                <h4>BEAT = PLACEMENT</h4>
                <p>Seeing a note appear on the visual is the indication of beat. They shoot out from the center to their position around the circle.</p>
            </div>
            <div class="fourth">
                <h4>DURATION = SIZE</h4>
                <p>Once the notes are placed, they continue to grow until the hand is removed and the note is no longer being played.</p>
            </div>
            <img class="vis-example first-vis-example" alt="visualzation example" src="assets/projects/beam-beats/song-lagrange.jpg">
            <img class="vis-example" alt="visualzation example" src="assets/projects/beam-beats/song-logical.jpg">
            <img class="vis-example" alt="visualzation example" src="assets/projects/beam-beats/song-wannabe.jpg">
        </div>
    </section>
    <section id="physical" class="bg-white">
        <div class="content">
            <h1>Physical Instrument</h1>
            <div class="half-first">
                <img style="width:100%; height:318px;" alt="physical instrument" src="assets/projects/beam-beats/physical1.jpg">
            </div>
            <div class="half">
                <img style="width:100%; height:318px;" alt="physical instrument" src="assets/projects/beam-beats/physical2.jpg">
            </div>
            <p style="margin-top: 370px;">After considering various instruments, our team agreed on implementing a guitar. We decided to utilize light to create the strings and allow users to interact with the light to create music. We utilized 2 short throw projects and mirrors to create 4 rays of light in different colors. When users interact with the light, a computer vision system tracks the location of their hand and plays the proper note.</p>
        </div>
    </section>
</div>

<?php require_once("build/footer.php"); ?>

</BODY>
</HTML>
